//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MultiLanguages.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BuildingWebApps {
            get {
                return ResourceManager.GetString("BuildingWebApps", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        public static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        public static string CurrencyText {
            get {
                return ResourceManager.GetString("CurrencyText", resourceCulture);
            }
        }
        
        public static string ApplicationDescriptionTitle {
            get {
                return ResourceManager.GetString("ApplicationDescriptionTitle", resourceCulture);
            }
        }
        
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        public static string ApplicationFeaturesTitle {
            get {
                return ResourceManager.GetString("ApplicationFeaturesTitle", resourceCulture);
            }
        }
        
        public static string LocalizationFeature {
            get {
                return ResourceManager.GetString("LocalizationFeature", resourceCulture);
            }
        }
        
        public static string GlobalizationFeature {
            get {
                return ResourceManager.GetString("GlobalizationFeature", resourceCulture);
            }
        }
        
        public static string TimeZoneFeature {
            get {
                return ResourceManager.GetString("TimeZoneFeature", resourceCulture);
            }
        }
        
        public static string TechnologyTitle {
            get {
                return ResourceManager.GetString("TechnologyTitle", resourceCulture);
            }
        }
        
        public static string ASPNetDescription {
            get {
                return ResourceManager.GetString("ASPNetDescription", resourceCulture);
            }
        }
        
        public static string JavaScriptDescription {
            get {
                return ResourceManager.GetString("JavaScriptDescription", resourceCulture);
            }
        }
        
        public static string ResxDescription {
            get {
                return ResourceManager.GetString("ResxDescription", resourceCulture);
            }
        }
        
        public static string CultureInfoDescription {
            get {
                return ResourceManager.GetString("CultureInfoDescription", resourceCulture);
            }
        }
        
        public static string PracticalImportanceTitle {
            get {
                return ResourceManager.GetString("PracticalImportanceTitle", resourceCulture);
            }
        }
        
        public static string PracticalImportance {
            get {
                return ResourceManager.GetString("PracticalImportance", resourceCulture);
            }
        }
    }
}
